### ISSUE TITLE
How to use in Nextcloud UI?

### ISSUE THREAD

**Issue by maxju** [nextcloud/text2image_stablediffusion#10]
This is a very basic question but I am quite clueless right now.
Nowhere do I find any hint to where in the Nextcloud Interface I can use this.

I did download the model and when I go to "Administration Settings" -> "Local Text to Image.." it says "Machine learning models have been downloaded successfully.". I went to "Artificial Intelligence" and selected the local option for text to image.

I tried the new Nextcloud Assistant (top right corner) but it only gives me options for LLM. 
When I type "/" in a text document it gives me the option for OpenAI.

How can I use the local text to image model?

**Comment by potagerGit** [comment]
I had the same issue : you have to install "text2image_helper app", and for me a new "smart picker" options "AI image generation" appears

**Comment by maxju** [comment]
> I had the same issue : you have to install "text2image_helper app", and for me a new "smart picker" options "AI image generation" appears

Thanks! This can be found in Apps / Tools
