### ISSUE TITLE
"AI image generation" task for "Nextcloud Assistant" has failed

### ISSUE THREAD

**Issue by bzzzggz** [nextcloud/text2image_stablediffusion#12]
Got a notification says generation failed.
![image](https://github.com/nextcloud/text2image_stablediffusion/assets/58054872/910b39e6-7f20-4cdb-bd6d-4292758861e2)
![image](https://github.com/nextcloud/text2image_stablediffusion/assets/58054872/3593d441-732f-4558-b0de-11fa73f5e36e)
AIO installed on QNAP through the container.
![image](https://github.com/nextcloud/text2image_stablediffusion/assets/58054872/c6067855-25e4-437d-8c6b-17600dc362c9)

**Comment by sbe-arg** [comment]
Share the nextcloud logs

**Comment by bzzzggz** [comment]
> Share the nextcloud logs

It's a test one, don't have the logs anymore. Thanks.
