### ISSUE TITLE
Use "Artificial Intelligence" admin section instead of "Connected accounts"

### ISSUE THREAD

**Issue by kyteinsky** [nextcloud/text2image_stablediffusion#14]
cc @marcelklehr

**Comment by marcelklehr** [comment]
This app is not using Connected Accounts, I believe. It has its own settings section

**Comment by kyteinsky** [comment]
Ah right, so do you think it makes sense to move it to the AI section? We're doing it for other apps like integration_openai and this app also falls in that basket.

**Comment by marcelklehr** [comment]
Yeah, might make sense :+1:
