### ISSUE TITLE
"To speed things up dramatically, install our node backend.."

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/text2image_stablediffusion#7]
Not sure if it is worth posting (or even possible), but when trying to generate an image, I see this in the logs:

> (node:10353) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
============================
Hi, looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, visit https://github.com/tensorflow/tfjs-node for more details

**Comment by marcelklehr** [comment]
Yes, this is by design. We only use tensorflow.js for minor calculations where the impact of not using the native version is negligible
